import { SpacingObject } from './typings';

export const QDR_SPACING: SpacingObject = {
  'spacing-0': '0rem',
  'spacing-1': '0.165rem',
  'spacing-2': '0.25rem',
  'spacing-3': '0.375rem',
  'spacing-4': '0.5rem',
  'spacing-5': '0.625rem',
  'spacing-6': '0.75rem',
  'spacing-7': '1rem',
  'spacing-8': '1.25rem',
  'spacing-9': '1.5rem',
  'spacing-10': '1.75rem',
  'spacing-11': '2rem',
  'spacing-12': '2.25rem',
  'spacing-13': '2.5rem',
  'spacing-14': '3rem',
  'spacing-18': '5rem',
  'spacing-21': '7.5rem',
  'spacing-24': '10rem',
  'spacing-25': '12.5rem',
  'spacing-27': '16rem',
  'spacing-28': '17.5rem',
  'spacing-30': '22.5rem',

  'radius-1': '0.25rem',
  'radius-2': '0.375rem',
  'radius-3': '0.5rem',
  'radius-4': '0.625rem',
  'radius-5': '0.75rem',
  'radius-6': '1rem',

  typographyArticleH1FontSize: '2rem',
  typographyArticleH1LineHeight: '1.4',
  typographyArticleH1LetterSpacing: '0',
  typographyArticleH1FontWeight: '600',

  typographyArticleH2FontSize: '1.5rem',
  typographyArticleH2LineHeight: '1.4',
  typographyArticleH2LetterSpacing: '0',
  typographyArticleH2FontWeight: '600',

  typographyArticleH3FontSize: '1.3125rem',
  typographyArticleH3LineHeight: '1.45',
  typographyArticleH3LetterSpacing: '0',
  typographyArticleH3FontWeight: '600',

  typographyArticleH4FontSize: '1.125rem',
  typographyArticleH4LineHeight: '1.45',
  typographyArticleH4LetterSpacing: '0',
  typographyArticleH4FontWeight: '600',

  typographyArticleH5FontSize: '1rem',
  typographyArticleH5LineHeight: '1.5',
  typographyArticleH5LetterSpacing: '0',
  typographyArticleH5FontWeight: '600',

  typographyArticleH6FontSize: '0.8125rem',
  typographyArticleH6LineHeight: '1.5',
  typographyArticleH6LetterSpacing: '0',
  typographyArticleH6FontWeight: '600',

  typographyArticleSubtitle1FontSize: '1rem',
  typographyArticleSubtitle1LineHeight: '1.5',
  typographyArticleSubtitle1LetterSpacing: '0',
  typographyArticleSubtitle1FontWeight: '400',

  typographyArticleBody1FontSize: '1rem',
  typographyArticleBody1LineHeight: '1.65',
  typographyArticleBody1LetterSpacing: '0',
  typographyArticleBody1FontWeight: '400',

  typographyArticleBody2FontSize: '0.8125rem',
  typographyArticleBody2LineHeight: '1.7',
  typographyArticleBody2LetterSpacing: '0',
  typographyArticleBody2FontWeight: '400',

  typographyBasicH1FontSize: '2rem',
  typographyBasicH1LineHeight: '1.5',
  typographyBasicH1LetterSpacing: '0',
  typographyBasicH1FontWeight: '600',

  typographyBasicH2FontSize: '1.5rem',
  typographyBasicH2LineHeight: '1.5',
  typographyBasicH2LetterSpacing: '0',
  typographyBasicH2FontWeight: '600',

  typographyBasicH3FontSize: '1.3125rem',
  typographyBasicH3LineHeight: '1.45',
  typographyBasicH3LetterSpacing: '0',
  typographyBasicH3FontWeight: '500',

  typographyBasicH4FontSize: '1.125rem',
  typographyBasicH4LineHeight: '1.55',
  typographyBasicH4LetterSpacing: '0',
  typographyBasicH4FontWeight: '500',

  typographyBasicH5FontSize: '0.9375rem',
  typographyBasicH5LineHeight: '1.6',
  typographyBasicH5LetterSpacing: '0',
  typographyBasicH5FontWeight: '500',

  typographyBasicH6FontSize: '0.8125rem',
  typographyBasicH6LineHeight: '1.5',
  typographyBasicH6LetterSpacing: '0',
  typographyBasicH6FontWeight: '500',

  typographyBasicButton1FontSize: '0.9375rem',
  typographyBasicButton1LineHeight: '2.65',
  typographyBasicButton1LetterSpacing: '0',
  typographyBasicButton1FontWeight: '500',

  typographyBasicButton2FontSize: '0.9375rem',
  typographyBasicButton2LineHeight: '2.15',
  typographyBasicButton2LetterSpacing: '0',
  typographyBasicButton2FontWeight: '500',

  typographyBasicButton3FontSize: '0.8125rem',
  typographyBasicButton3LineHeight: '1.85',
  typographyBasicButton3LetterSpacing: '0',
  typographyBasicButton3FontWeight: '500',

  typographyBasicInput1FontSize: '0.9375rem',
  typographyBasicInput1LineHeight: '2.65',
  typographyBasicInput1LetterSpacing: '0',
  typographyBasicInput1FontWeight: '400',

  typographyBasicInput2FontSize: '0.9375rem',
  typographyBasicInput2LineHeight: '2.15',
  typographyBasicInput2LetterSpacing: '0',
  typographyBasicInput2FontWeight: '400',

  typographyBasicInput3FontSize: '0.8125rem',
  typographyBasicInput3LineHeight: '1.85',
  typographyBasicInput3LetterSpacing: '0',
  typographyBasicInput3FontWeight: '400',

  typographyBasicBody1FontSize: '0.9375rem',
  typographyBasicBody1LineHeight: '1.6',
  typographyBasicBody1LetterSpacing: '0',
  typographyBasicBody1FontWeight: '400',

  typographyBasicBody2FontSize: '0.8125rem',
  typographyBasicBody2LineHeight: '1.5',
  typographyBasicBody2LetterSpacing: '0',
  typographyBasicBody2FontWeight: '400',

  typographyBasicCaptionFontSize: '0.75rem',
  typographyBasicCaptionLineHeight: '1.35',
  typographyBasicCaptionLetterSpacing: '0',
  typographyBasicCaptionFontWeight: '400',
};
